config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'user/new'
  get 'users/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/lessons', to: 'lessons#lesson'
  resources :lessons
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :active_relationships, class_name: "Relationship",
  foreign_key: "follower_id",
  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
  foreign_key: "followed_id",
  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
		
	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
		
	# Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def follow(other_user)
    following << other_user
  end
    
  def unfollow(other_user)
    following.delete(other_user)
  end
    
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    before_action :find_lesson, only: [:show, :edit, :update, :destroy]

    def lesson
        @lesson = Lesson.all.order("created_at DESC")
    end

    def show
    end

    def new
        @lesson = Lesson.new
    end

    def create
        @lesson = Lesson.new(lesson_params)

        if@lesson.save
            redirect_to @lesson, notice: "Successfully created new Lesson!"
        else
            render 'new'
        end
    end

    def edit
    end

    private

    def lesson_params
        params.require(:lesson).permit(:title, :description)
    end

    def find_lesson
        @lesson = Lesson.find(params[:id])
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in?
    
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end
        
  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end
    
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
      :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user && user == current_user
  end
  
  def logged_in?
    !current_user.nil?
  end

  def log_out
    reset_session
    @current_user = nil
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  # Logs out the current user.
  def log_out
    forget(current_user)
    reset_session
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The most awesome E-learning app!
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="https://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "E-LEARNING", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Lessons", lessons_path %></li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                    <%= link_to "Log out", logout_path, method: :delete %>
                    </li>
                </ul>
                </li>
            <% else %>
                <li><%= link_to "Log in", login_path %></li>
            <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag 'application', media: 'all',
        'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
            <%= render 'layouts/footer' %>
        </div>
    </body>
</html>

app/views/lessons/_form.html.erb
<%= form_for @lesson, html: { multipart: true } do |f| %>
    <% if @lesson.errors.any? %>
        <div id="errors">
            <p>
                <%= @lesson.errors.count %>
                Prevented this Lesson from saving
            </p>
            <ul>
                <% @lesson.errors.full_messages.each do |msg| %>
                    <li>
                        <%= msg %>
                    </li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="panel-body">
        <h2>Title</h2>
        <%= f.text_field :title, input_html: { class: 'form-control' } %>
        <h2>Description</h2>
        <%= f.text_field :description, input_html: { class: 'form-control' } %>
    </div>
    <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/lessons/lesson.html.erb
<%= @lesson.each do |lesson| %>
    <h2><%= link_to lesson.title %></h2>
<% end %>

app/views/lessons/show.html.erb
<h1><%= @lesson.title %></h1>
<p><%= @lesson.description %></p>

<%= link_to "Back", lessons_path, class: "btn btn-default" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
            <%= @user.following.count %>
        </strong>
        following
    </a>
    <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
            <%= @user.followers.count %>
        </strong>
        followers
    </a>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
    The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
    Tutorial</em></a>, part of the
    <a href="https://www.learnenough.com/">Learn Enough</a> family of
    tutorials, is a
    <a href="https://www.railstutorial.org/book">book</a> and
    <a href="https://screencasts.railstutorial.org/">screencast series</a>
    to teach web development with
    <a href="https://rubyonrails.org/">Ruby on Rails</a>.
    This is the sample app for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
    Contact the Ruby on Rails Tutorial about the sample app at the
    <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
    Get help on the Ruby on Rails Tutorial at the <a href="https://www.railstutorial.org/help">Rails Tutorial Help page</a>.
    To get help on this sample app, see the
    <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
    book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <h1>AWESOME!</h1>
    <h2>
    You made it this far? Congrats!
    </h2>
    <section class="stats">
        <%= render 'shared/stats' %>
    </section>
<% else %>
    <div class="center">
        <h1>AWESOME!</h1>
        <h2>
            You made it this far? Congrats!
            <br>
            <br>
            Now, click the sign-up button and let the magic begins. 
        </h2>
        <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>
<% end %>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
            <%= render 'unfollow' %>
        <% else %>
            <%= render 'follow' %>
        <% end %>
    </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
html: { method: :delete }, local: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
    data: { confirm: "You sure?" } %>
    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @user, local: true) do |f| %>
            <%= render 'shared/error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>
        <div class="gravatar_edit">
            <%= gravatar_for @user %>
            <a href="https://gravatar.com/emails" target="_blank">change</a>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @user, local: true) do |f| %>
            <%= render 'shared/error_messages' %>
            <%= f.label :name, class: "text" %>
            
            <%= f.text_field :name, class: 'form-control' %>
            <%= f.label :email, class: "text" %>
            
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label :password, class: "text" %>
            
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :password_confirmation, "Confirmation", class: "text" %>
            
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user, class: "picture" %>
                <%= @user.name %>
            </h1>
        </section>
        <section class="stats">
            <%= render 'shared/stats' %>
        </section>
        <%= render 'follow_form' if logged_in? %>
    </aside>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <%= gravatar_for @user %>
            <h1><%= @user.name %></h1>
        </section>
        <section class="stats">
            <%= render 'shared/stats' %>
            <% if @users.any? %>
            <div class="user_avatars">
                <% @users.each do |user| %>
                    <%= link_to gravatar_for(user, size: 30), user %>
                <% end %>
            </div>
            <% end %>
        </section>
    </aside>
    <div class="col-md-8">
        <h3><%= @title %></h3>
        <% if @users.any? %>
            <ul class="users follow">
            <%= render @users %>
            </ul>
        <% end %>
    </div>
</div>